### ISSUE TITLE
Remove json support in master

### ISSUE THREAD

**Issue by baylej** [baylej/tmx#11]
Because:
* XML is sufficient
* Hard to maintain two file formats
* Time consuming to maintain ...
* Json format is more suitable for Javascript than C/C++
* Probably not widely used (previous point)

Todo: Create a branch on the last commit with JSON support.

**Comment by PedroHLC** [comment]
Are you sure about this? you did a good job implementing JSON. And, in some ways, the json specification does make part of the TMX project, so it should be part of any implementation of it...

**Comment by baylej** [comment]
Hi @PedroHLC,

I think without json we will have more contributions, because anyone willing to add a feature won't have to implement it into the json parser, especially if they don't use the json format in their games.

The json parser won't be thrown in the garbage, I will keep it in a branch and I (or someone else) will work on it.

Then we will have branch `master` containing the xml parser, and branch `json` which adds the json parser.

**Comment by bjorn** [comment]
I know it's been a while, but I only just found out this lib doesn't actually do JSON after reading that it does on the [libraries and frameworks page](http://doc.mapeditor.org/en/latest/reference/support-for-tmx-maps/#c). I'll adjust that reference.

And I just wanted to add that I think removing JSON support was a good decision. In fact in hindsight I sometimes wish I would have kept the JSON format in Tiled purely as an export option rather than boosting it as a full TMX alternative. It's really a hassle to support two file formats.
