### ISSUE TITLE
Add makefile or instructions for examples

### ISSUE THREAD

**Issue by PMunch** [baylej/tmx#30]
Title says it all really. For a quick and easy check of what this project can do it should be easy to run the examples, currently you have to figure out how to compile it before you can get anywhere.

**Comment by baylej** [comment]
Hi, I agree, this is missing.

**Comment by Oo8z** [comment]
I don't know how to implement this on a .c file, anyone can help me ?

**Comment by mupfelofen-de** [comment]
https://github.com/mupfelofen-de/janitor-jamboree

Well, yesterday I figured out how to compile it using a Makefile and also add it directly to my project. Much easier to distribute this way.

Check it out. In case it doesn't work for you, I would happy to assist you further.

PS: It just compiles for me now. Haven't tried anything useful yet. I'm also using SDL1 instead of 2.

Michael

**Comment by baylej** [comment]
CMake `CMakeFile.txt` build scripts have been added (unfortunately they only work on linux).

The raylib library does not properly set the interface of its exported targets, a few dependencies are missing and have to be added for the example to build (breaks portability).

The Allegro5 and SDL2 examples depend on the pkg-config utility (only available on unixes).

It is possible to improve these CMake scripts but I don't want to spend too much time there.
