### ISSUE TITLE
Build fails on MacOS Mojave due to not finding LibXML2

### ISSUE THREAD

**Issue by edin-m** [baylej/tmx#51]
I've built my own libxml2 and installed into a custom folder.

Running the build of tmx failed when trying to point cmake to this folder.

```
cmake .. -DCMAKE_INSTALL_PREFIX=/Users/edin-m/del/mygame/lib/install -DCMAKE_PREFIX_PATH=/Users/edin-m/del/mygame/lib/install

Imported target "LibXml2::LibXml2" includes non-existent path
```

Changing `target_link_libraries(tmx LibXml2::LibXml2)` to `target_link_libraries(tmx LibXml2)` in `CMakeLists.txt` fixed the issue.

**Comment by baylej** [comment]
This is weird because the FindLibXML2 cmake script should be the same, and work the same across platforms.

As [they recently added a CMakeList.txt build script](https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/73), LibXml2 now officially exports the `LibXml2::LibXml2` target, therefore the FindLibXML2 cmake script is no longer necessary, but the last time I checked, no official release included that build script.

Also as I don't own a Mac, I can't really help. Glad you got it to compile and work.
