### ISSUE TITLE
tmx_tile has an inefficient storage method (linked list)

### ISSUE THREAD

**Issue by baylej** [baylej/tmx#8]
A linked list is inefficient here because we need random access to a given tile.

Two propositions:

→ **Array**, random access,
Pros: easy to implement.
Cons: large memory footprint with a lot of tiles and a few `tmx_tile` to store.

→ **Hashtable** using the tile `gid` as the key, linked-list for collisions, almost random access,
Pros: little memory footprint for sparse data.
Cons: cumbersome to implement.

Tiled uses a `QList` (array based) to store instances of `Tile`.

I personally prefer the array, to keep the code simple.

**Comment by RPGHacker** [comment]
I'd also go with an array implementation to keep it simple. My idea is to make it a sorted dynamic array (by inserting a tile in the correct, sorted array location on creation). Should still be quite simple to implement, but that way we could at least use binary search and binary insertion to make it somewhat fast, even with a big number of tiles (only around 20 comparisons for one million tiles, for example). Only major contra would be slow resizing of arrays (copying/moving array elements), but I suppose that this wouldn't be too much of a problem since a very high number of tiles is very unlikely (I could imagine, maybe, a few thousand different tiles at worst). And at least it would only be slow during the creation of a tmx_map, after that it wouldn't have to move any data around anymore and at least would be quite fast for searching (at least faster than a linked list). I could implement this if you agree to this approach.

**Comment by baylej** [comment]
Hi,

I think i'll use https://github.com/nothings/stb/blob/master/stretchy_buffer.h for tmx files made by QtTiled < 0.12, then i'll use `tilecount`.

**Comment by RPGHacker** [comment]
Are these stretchy buffers sorted? (For finding tiles faster)
Have you looked into my pull request yet? Will  you use this instead of my sorted array implementation? Or are you making another branch?

Regards

**Comment by baylej** [comment]
Hi @RPGHacker,

I looked at your PR, it works fine, but you should have added new tiles at the end of a dynamic array, and have sorted the array afterwards using the standard `qsort` function, to reduce the length of the code.
And because there will probably never be a lot of tiles, a sparse array is fine, and is also better for performances.
For these reasons, your PR won't make it to the master.

I pulled your PR in a branch to rework it and merge the animated tiles support into the master (Not done yet, but on my personal todolist).

Thank you for your contributions @RPGHacker, I hope you don't hate me.
kind regards.

**Comment by RPGHacker** [comment]
Nah, why would I hate you for this? ;)
Just wanted to get a status update and some criticism to know what I can improve. I agree with everything you said, it would probably be faster in most (if not all) cases to just insert the tiles unsorted in the array (less moving around of memory during map construction) and then sort everything at the end. There are a few occassions when the map loader actually searches for tiles in the array during map construction (in the JSON version), that is why I decided to make it a sorted array. Though this is probably still slower than not sorting the elements and iterating over the array during map construction, so I acknowledge your suggestion.

**Comment by baylej** [comment]
I forgot about the json parser ... again.
I don't understand why I added support for the json format, I don't use it, and it's more suitable for javascript than C/C++.

**Comment by RPGHacker** [comment]
Yeah, more formats just means more code to maintain and for anyone using the library it should really be enough to have support for just a single format. I think at this point it wouldn't hurt anyone to just drop JSON support from the library completely. That would also make future updates a lot easier (and there are a lot of them since Tiled is currently progressing quite fast thanks to Bjorn's Patreon).

**Comment by baylej** [comment]
Hi @RPGHacker,

I made something, look at commit c448da3 in the *wip* branch:
it uses the new `tilecount` attribute to allocate a array of the right size, then after the loading pass, it creates a global array of pointers to `tmx_tiles` whose index is the GID.

I'd really appreciate your feedback, if you are still interested in this lib.

Thanks.

**Comment by RPGHacker** [comment]
Sounds like a great way to solve the problem! Yeah, that should really speed things up, while also greatly reducing the amount of code. I like this solution, good job!
