### ISSUE TITLE
Cannot load map: xml parser: an error occured in the delegated image loading function

### ISSUE THREAD

**Issue by 3dgoose** [baylej/tmx#82]
`Cannot load map: xml parser: an error occured in the delegated image loading function` when using the SDL example compiled with the CMakeLists.txt.

`./sdl_example untitled.tmx`

**Comment by baylej** [comment]
Hello,

There is too little context here for me to help you.
Image loading does work, have you tried one of the examples shipped with this project ? (in folder examples/data) 

eg: `./sdl_example ../data/csv.tmx`

**Comment by 3dgoose** [comment]
How to do it ?

**Comment by baylej** [comment]
If you investigate this error, you'll find that it is caused by the `tmx_img_load_func` callback, in the SDL example it's set to the `SDL_tex_loader`
See: https://github.com/baylej/tmx/blob/11ffdcdc9bd65669f1a8dbd3a0362a324dda2e0c/examples/sdl/sdl.c#L12

For some reason, the image could not be loaded into a texture, but this is happening in SDL2, not in libTMX !

**Comment by 3dgoose** [comment]
Euh, I know it's not approptiate, but could you help me fix it ?

**Comment by baylej** [comment]
Sorry, I can't help, I'm on my phone, I don't have your files, I'm not well-versed in SDL2 programming, ...
You should ask for help on the discord of the SDL project, plus don't forget that Tiled has a discord as well where you can get help.

**Comment by 3dgoose** [comment]
I'll try stackoverflow.
